# Generated by Django 4.0.6 on 2022-10-16 10:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('level', models.CharField(blank=True, choices=[('CRECHE', 'CRECHE'), ('NURSERY', 'NURSERY'), ('PRIMARY', 'PRIMARY')], max_length=255, null=True)),
                ('sex', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=10)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('Birthplace', models.CharField(blank=True, max_length=255)),
                ('home_address', models.TextField(blank=True, max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parent.parent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
