# Generated by Django 4.0.6 on 2022-10-11 10:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, choices=[('MR', 'MR'), ('MRS', 'MRS')], max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('parent_phone', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('sex', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=10)),
                ('level', models.CharField(blank=True, choices=[('CRECHE', 'CRECHE'), ('NURSERY', 'NURSERY'), ('PRIMARY', 'PRIMARY'), ('JUNIOR SECONDARY', 'JUNIOR SECONDARY'), ('SENIOR SECONDARY', 'SENIOR SECONDARY')], max_length=255)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('Birthplace', models.CharField(blank=True, max_length=255)),
                ('home_address', models.TextField(blank=True, max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.parent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
