# Generated by Django 4.1.1 on 2022-09-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('sex', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='', max_length=10)),
                ('level', models.CharField(blank=True, choices=[('CRECHE', 'CRECHE'), ('NURSERY', 'NURSERY'), ('PRIMARY', 'PRIMARY'), ('JUNIOR SECONDARY', 'JUNIOR SECONDARY'), ('SENIOR SECONDARY', 'SENIOR SECONDARY')], max_length=255)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('Birthplace', models.CharField(blank=True, max_length=255)),
                ('home_address', models.TextField(blank=True, max_length=255)),
                ('phone', models.IntegerField(blank=True, max_length=255, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('parent_phone', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
