# Generated by Django 4.1.1 on 2022-09-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
