# Generated by Django 4.0.6 on 2022-10-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_type',
            field=models.CharField(blank=True, choices=[('BASIC PRIMARY', 'BASIC PRIMARY'), ('SECONDARY', 'SECONDARY')], max_length=255),
        ),
    ]
