# Generated by Django 3.2 on 2022-09-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_parent_alter_parent_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='title',
            field=models.CharField(blank=True, choices=[('MR', 'MR'), ('MRS', 'MRS')], max_length=255, null=True),
        ),
    ]
