# Generated by Django 3.2 on 2022-09-25 09:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_parent_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
