# Generated by Django 4.0.6 on 2022-09-28 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('sex', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=255)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('religion', models.CharField(blank=True, choices=[('ISLAM', 'ISLAM'), ('CHRISTIANITY', 'CHRISTIANITY')], max_length=255, null=True)),
                ('classlevel', models.CharField(blank=True, choices=[('CRECHE', 'CRECHE'), ('NURSERY', 'NURSERY'), ('PRIMARY', 'PRIMARY'), ('JUNIOR SECONDARY', 'JUNIOR SECONDARY'), ('SENIOR SECONDARY', 'SENIOR SECONDARY')], max_length=255, null=True)),
                ('education_background', models.CharField(blank=True, choices=[('COLLEGE OF EDUCATION', 'COLLEGE OF EDUCATION'), ('UNIVERSITY', 'UNIVERSITY')], max_length=255, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=255, null=True)),
                ('special_skills', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Teachers',
            },
        ),
    ]
