# Generated by Django 4.0.6 on 2022-10-11 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(blank=True, choices=[('CRECHE', 'CRECHE'), ('PRIMARY', 'PRIMARY'), ('JUNIOR SECONDARY', 'JUNIOR SECONDARY'), ('SENIOR SECONDARY', 'SENIOR SECONDARY')], max_length=255, null=True)),
                ('qualification', models.CharField(blank=True, choices=[('NCE', 'NCE'), ('OND', 'OND'), ('HND', 'HND'), ('BSC', 'BSC')], max_length=255, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'SINGLE'), ('ENGAGED', 'ENGAGED'), ('MARRIED', 'MARRIED')], max_length=50, null=True)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('experience', models.TextField(blank=True, max_length=255, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
